### ISSUE TITLE
Time Axis based on Market Timings

### ISSUE THREAD

**Issue by prasad1247** [tvjsx/trading-vue-js#102]
Hi, First of all, this is great work. !!
Can we have the time axis based on a market's opening and closing times? Currently, When I plot the data it shows gaps in it. 

![image](https://user-images.githubusercontent.com/5327738/80726187-fcbeab80-8afb-11ea-975b-df86835fa1f5.png)

**Comment by C451** [comment]
Hello my friend, It's called index-based rendering & it will be in the next release (0.5.0) 
Clone this repo and `npm run test` test 2

**Comment by prasad1247** [comment]
Thank You !! It is now removing the gaps and showing as expected..
