### ISSUE TITLE
Candles sometimes have no width (and zoom is locked to minimum scale)

### ISSUE THREAD

**Issue by tiagosiebler** [tvjsx/trading-vue-js#103]
## Description
I've noticed only sometimes (not always with this candle+indicator combination) that candles show as single lines and the chart zoom is locked to a minimum. This is reproducible with the latest version of the 101 project, with my dataset.

## Screenshot (if applicable)
<img width="1442" alt="Screenshot 2020-05-03 at 11 15 07" src="https://user-images.githubusercontent.com/14090872/80911627-61158100-8d2f-11ea-8e8f-6df038264fb7.png">

## Data Sample (if applicable)
Zipped data.json - use instead of the data.json in the 101 project:
[data_weirdCandles.json.zip](https://github.com/tvjsx/trading-vue-js/files/4569999/data_weirdCandles.json.zip)

## Console errors (if any)
None seen

## Additional Info 
All on latest / default.

**Comment by C451** [comment]
The first thing to check is that timeframe detected correctly & candles are following that timeframe step (gaps are allowed)

**Comment by tiagosiebler** [comment]
[tinycandles.json.zip](https://github.com/tvjsx/trading-vue-js/files/4608935/tinycandles.json.zip)
Another data sample - I really need to spend some time on this, as it's getting annoying haha:
![Screenshot 2020-05-11 at 11 10 41](https://user-images.githubusercontent.com/14090872/81550408-1374c600-9378-11ea-980f-97790beef3e3.png)

@C451 you've mentioned checking if timeframe is detected correctly, is there a part of tvjs I should debug in this scenario?

Regarding timeframe step, do you suspect there might be overlapping timestamps, or what were your thoughts?

**Comment by C451** [comment]
@tiagosiebler we have a new solution now, try to use 
```
"chart": { 
     "tf": <yo timeframe>
}
```

**Comment by tiagosiebler** [comment]
Thanks @C451 - is this in this tree of the chart dataset?
https://github.com/tvjsx/trading-vue-101/blob/master/data/data.json#L2

What's the datatype for the "tf" property? Can you provide an example for 5 minute candles?

**Comment by C451** [comment]
Literally, 
```
"chart": { 
     "tf": <yo timeframe>
}
```
Or test's #11 data 
Tiago, what happened to you? You are a tvjs OG :D

**Comment by tiagosiebler** [comment]
Finally managed to spend time on this...can confirm, happens when the dataset has duplicate candles. Oops!
