### ISSUE TITLE
Indicator id and overlay id do not match

### ISSUE THREAD

**Issue by pdwinkel** [tvjsx/trading-vue-js#106]
## Description
The indicator id and overlay id do not match.

## Console logging
When a legend button is selected you get the following event:
`
{button: "display", type: "onchart", dataIndex: 1, grid: 0, overlay: "EMA_1"}
`
with overlay id `EMA_1`.

But DataCube has the following onchart entry:
`
{id: "onchart.EMA1", …}
`
with id `EMA1`, without the underscore.

#### Code lines
[Legend](https://github.com/tvjsx/trading-vue-js/blob/master/src/components/Legend.vue#L75)
[DataCube](https://github.com/tvjsx/trading-vue-js/blob/master/src/helpers/dc_core.js#L101)

**Comment by C451** [comment]
That's because these are different ids (think of DC as an extension). You supposed to use 
`dataIndex: 1, grid: 0` to get the right overlay.

**Comment by pdwinkel** [comment]
OK, was following the test code of LegendButtons.vue, which uses:
`
let d = this.chart[event.type][event.dataIndex]
`
So it should be something like:
`
dc.get(event.type)[event.dataIndex]
`
?
Where comes the `grid` in play?

**Comment by C451** [comment]
Yeah, `dc.get(event.type)[event.dataIndex]` this is the right way.

**Comment by pdwinkel** [comment]
Yes, display on/off works.
Thx
