### ISSUE TITLE
Add multiple charts

### ISSUE THREAD

**Issue by salakhovilia** [tvjsx/trading-vue-js#108]
## Description
It would be great if there was the possibility of adding multiple charts to one workspace
## Screenshot (if applicable)
![image](https://user-images.githubusercontent.com/47942484/83944800-59a63380-a817-11ea-9ef8-545e484bfe30.png)

## Data Sample (if applicable)

The data sample must follow the current [data structure](https://github.com/C451/trading-vue-js/tree/master/docs/api#data-structure-new).

## Additional Info 

(if needed to reproduce the issue) 

(tvjs version, OS, browser, npm version...)

**Comment by arunavo4** [comment]
@salahovilia https://github.com/tvjsx/trading-vue-js/blob/master/test/tests/Multichart.vue

**Comment by C451** [comment]
To be implemented in your app & connected with https://github.com/tvjsx/tvjs-xp
