### ISSUE TITLE
How to donate

### ISSUE THREAD

**Issue by stkbt** [tvjsx/trading-vue-js#110]
Hi guys,
Thanks for the great job. I want to support you with money, so how I can do it?
May be you can start campaign on Patreon or activate `Sponsor`  button on GitHub.

**Comment by C451** [comment]
Hey, only BTC or ETH for now
19vDB2pyn2ndJBH4p6We2SJNe8VZggyxfG
0xFD3e4be6d3dAfCba7aFC7BE8b3D00847682158e8

**Comment by stoxalpha** [comment]
Amazing. Very glad to see this.

**Comment by C451** [comment]
@stkbt 🍻
