### ISSUE TITLE
Add a data point and redraw chart

### ISSUE THREAD

**Issue by ivopashov** [tvjsx/trading-vue-js#111]
Hi,

I am having the following scenario and I am trying to figure out what is the best way to accomplish:

I draw a historical chart and allow the user to move forward. Move forward means that a data point is added to the existing ones. For example you have all the OHCLV for 1.1.2000 - 31.01.2000 and those are charted. Then you want dynamically to add data for 1.2.2000, 2.2.2000 etc. 

I figured that you can update/merge data on the DataCube instance but am not sure what is the best way to redraw the chart. 

Thanks

**Comment by C451** [comment]
Hey, I think you need `goto()` , look into the API Book

**Comment by ivopashov** [comment]
Yep, that seems to work. Thanks!
