### ISSUE TITLE
Real Time Data from MetaTrader V

### ISSUE THREAD

**Issue by alejandrofg** [tvjsx/trading-vue-js#112]
**Good morning everyone:**

Thank you very much first of all for reading this thread and especially for your patience.

I have first been reading the issues raised and the documentation sorry if I repeat the topic.

I am seeing that it is an excellent work and I want to apply it under the metatrader V trading tool.

This tool provides real-time data from different brokers as well as a multitude of customizable tools, trading information, etc.

Given the ease that MT5 presents and I have thought about using it together with trading-vue and showing my tools through the web, it is the weak point of metatrader or mt5 that its web platform cannot replicate your custom indicators.

Now  it is currently possible to export from MT5 or Metatrader data in SQL (Mysql) both fixed (without adding data in real time) or in real time).

I see that it is more manageable to dump prices to MYSQL and from there import the data into trading-vue, since a file, in the long run, can cause problems especially with very large histories (years), although it is not a problem since We are going to use real time and with a small period or interval of history is enough.

Well the case that I do not understand well how trading-vue would inject the data in real time, from SQL.

I understand that you are importing data from a url as plain text (correct me).

Well, why don't we use sql, php and mt5?

I'm not a programming genius, I'm still learning things and it's hard for me.But i help from mt5, mysql, php......

Would you like to create something like this?

Use vue.js, maybe trading-vue.js to get sql info....for example.

I have seen in this link how they use vue.js for real time:

https://apifriends.com/api-streaming/streamdataio-vue-js-sample-realtime/

But I don't know exactly how to fit all this in a first phase to acquire data from sql.

Very kind and thanks.

**Comment by C451** [comment]
@alejandrofg Thanks for the suggestion 

Personally I don't use any existing trading software so the current .json format was chosen because its simplicity. 

But I think the problem can be solved with some kind of converter script.

**Comment by alejandrofg** [comment]
Hi!:

I need a days to thinks about this idea, soon i write you again.

Thanks!!

**Comment by alejandrofg** [comment]
@C451 👍 

Doy you have any example with real time?

Thanks!
