### ISSUE TITLE
Chart “jumps” when index-based and onRange are combined

### ISSUE THREAD

**Issue by michael-k** [tvjsx/trading-vue-js#113]
### Background

A while ago I've [asked in Discord](https://discord.com/channels/692731556288004116/693033639528890378/715934423714889778) about the chart jumping when `index-based` and `onRange` are combined.  Here's finally the bug report for that.

### Actual Description

When `index-based` is set to `true` and `DataCube.onrange` is used to lazy load older candles, the chart jumps when older candles are added to the chart.  Jumping means, that the left-most candle of the updated chart is drawn where the left-most candle of the previous chart was.

It also happens often that `onrange` fires again and again (worst case: until no more data is available), moving the original chart all the way to the right.

### Minimal example

Here's a minimal example that reproduces the problem with the data sample from below.  I've put all the files in one place and started a minimal web server with `python3 -m http.server 8000`. (Sorry, I'm more familiar with the Python ecosystem than the one from Node.js/Javascript.)

<details><summary>index.html</summary>

```html
<html>
<head>
  <title>TradingVue</title>
  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/trading-vue-js@0.5.1/dist/trading-vue.min.js"></script>
</head>
<body>
  <h1>TradingVue</h1>
  <div id="app">
    <trading-vue :data="chart" :index-based="indexBased"></trading-vue>
  </div>
  <script>
  var app = new Vue({
    el: '#app',
    data() {
      return {
        indexBased: true,
        chart: {},
        minRequested: 5
      }
    },
    async created() {
      const res = await window.fetch('05.json');
      const ohlcv = await this.ohlcvFromResponse(res);
      this.chart = new TradingVueJs.DataCube({
        ohlcv,
        onchart: [],
        offchart: []
      });
      this.chart.onrange(this.load_chunk);
    },
    methods: {
      async load_chunk(range) {
        console.log('REQUESTED RANGE', JSON.stringify(range));
        if (range[0] > 0) return [];
        if (this.minRequested === 1) return [];
        this.minRequested -= 1;
        const res = await window.fetch('0' + this.minRequested + '.json');
        return await this.ohlcvFromResponse(res);
      },
      async ohlcvFromResponse(res) {
        if (!res.ok) return [];
        const data = await res.json();
        return data.map(d => {
          d[0] = new Date(d[0]).getTime();
          return d.map(v => v * 1);
        });
      }
    }
  })
  </script>
</body>
</html>
```

</details>

## Screenshot

Screen captures are availabe in Discord:
- `index-based=false`: https://discord.com/channels/692731556288004116/693033639528890378/715942896758554774
- `index-based=true`: https://discord.com/channels/692731556288004116/693033639528890378/715942956925714433

## Data Sample

Sorry for not following the [data structure](https://github.com/C451/trading-vue-js/tree/master/docs/api#data-structure-new).  I've created the minimal example first and only then saw this requirement.  The provided data can be used in combination with the `index.html` from above.  I can rewrite the data to match the requested data structure if necessary. :)

[index-based-and-onrange.zip](https://github.com/tvjsx/trading-vue-js/files/4808040/index-based-and-onrange.zip)

## Console errors

n/a

## Additional Info 

- tvjs version: 0.5.1
- bowser: Firefox 77.0.1

**Comment by C451** [comment]
@michael-k probably has something to do with #104 
BTW the best issue description so far.

**Comment by C451** [comment]
That was one hell of a bug, testing is needed.
