### ISSUE TITLE
Offchart - Request for overlapping indicators to be included in the same offchart (Enhancement)

### ISSUE THREAD

**Issue by test513607a** [tvjsx/trading-vue-js#114]
The offcharts seem to work for one indicator at a time 
if i have multiple overlapping indicators within the range , then a separate offchart is getting created

can the overlapping be introduced base on a common param between the combining offcharts

**Comment by C451** [comment]
This is undocumented yet, there is `grid` property in overlay object: 
```js
{
  grid: {
    id: <new_id> // 0 - main grid, 1 - first offchart, etc
  }
}
```

**Comment by novecento** [comment]
What is the grid-id pattern to overlay 4 offchart Splines, "2 with 2" ?
a-b
c-d
