### ISSUE TITLE
Request for splitter to be added to offchart 

### ISSUE THREAD

**Issue by test513607a** [tvjsx/trading-vue-js#116]
The splitter functionality is present on onchart, but not on offchart..

**Comment by C451** [comment]
Hmmmm, that's strange, should work on both by design

**Comment by test513607a** [comment]
Its not working yet C451 :(

**Comment by C451** [comment]
I mean you need to add the overlay to every sub chart (for now there are no cross-grid overlays)

**Comment by test513607a** [comment]
hmmm ok 
will check that
