### ISSUE TITLE
Timestamp representation on the x-axis , weird jump

### ISSUE THREAD

**Issue by test513607a** [tvjsx/trading-vue-js#117]
Timestamp string representation on the botbar has an issue 

Example:
the time 25th Jun 0:00 - 4:00 appears at the end of the day Jun25th day, the same continues for everyday

<------------25------------------------>|<------------26------------>
<25: 4am-12night><25:0 am - 4 am>|<26: 4am-12night><26:0 am - 4 am>

the timestamp string representation alone should have been an error.(something to do with localtime vs GMT time representation? )
[data - Copy.zip](https://github.com/tvjsx/trading-vue-js/files/4874225/data.-.Copy.zip)

**Comment by C451** [comment]
Nice catch,
btw use the issue template next time

**Comment by test513607a** [comment]
Thanks.
will check to use the issue template.

**Comment by test513607a** [comment]
Unlike TradingView, and other graphs , a day is represented before its date is displayed on x-axis
ie todays date being 9 th on  the x-axis we dont see  9, rather 8 is seen and candles appearing after it pertain to the todays

8th , 9th of a month represented appropriately.

<-------8th------><-------9th------>

x: axis : TradingVue
===========8===========9
x:axis : TradingView
8==========9===========10
Do you think the regular standard is to be implemented

**Comment by C451** [comment]
I believe I fixed that in the commit above, didn't build the dist yet.

**Comment by test513607a** [comment]
You fixed the jump as mentioned in the bug initially, this is not actually a bug, this is where we represent the day on the x-axis 
after the day is over or before the day starts 
tradingView starts it with that day 
TradingVue ends it with that day

**Comment by C451** [comment]
Maybe you need to set UTC on tv.com
![compare_tv_tvjs](https://user-images.githubusercontent.com/48596328/87156706-c5236b00-c2c5-11ea-9674-fc49ebcac3e8.png)

**Comment by test513607a** [comment]
hmmm 
thats(tradingVue time axis) is different for me
9 shows up wherer it shows 10 for you . Will check
Thanks for responding
