### ISSUE TITLE
Clusters or footprint

### ISSUE THREAD

**Issue by zoh** [tvjsx/trading-vue-js#118]
Hello

I wanna create a custom overlay (or chart) chart like this.
![image](https://user-images.githubusercontent.com/1598229/86767233-5a1f2d80-c054-11ea-848b-55c8b085959a.png)

How can I update code to update width of candles for render custom clusters?

#qustions

**Comment by C451** [comment]
https://tvjs.io/play?a=rark01wc

but you still need a custom overlay
