### ISSUE TITLE
Action based on a trendline touched trigger? 

### ISSUE THREAD

**Issue by Edensplash** [tvjsx/trading-vue-js#120]
Is it possible to make an automatic order or other action based on a trendline touched trigger ?

**Comment by C451** [comment]
This is a rendering-only lib, but the answer: yes, in your app.

**Comment by Edensplash** [comment]
I see.  When I draw a trendline how can i get value of each trendline points (coordinates)  for every Timeframe unit ?  because i suppose in the app i need to compare the coordinates of the trendline point and the value of the candle chart to see if  the trendline i draw is touching the candle chart on a  specific timeframe (for example minute in my case)

**Comment by C451** [comment]
The line points are in the overlay's `settings` object (see LineTool.vue). All you need is to apply a simple math.

**Comment by Edensplash** [comment]
Ok Thanks
