### ISSUE TITLE
Zoom and timestep problem

### ISSUE THREAD

**Issue by adsonvinicius** [tvjsx/trading-vue-js#125]
I spent the last days reading about this library and I found that could help in my real-time candle-sticks at 15 minute period.
I don't know if is the magic mouse (osx chrome) behavior but the zoom in-out tool doesn't works fine, it depends on which period of time is shown to zoom-in/out. Quite strange for me.

Scrolling left (on periods before data rendered) it crashes (even if no log is shown on console) and it's not possible see data anymore scrolling right. 

I saw some posts about the minimal example published not working properly because amount of data, so I'm a bit confused about this behavior.

**Comment by Edensplash** [comment]
I think it will be great if we can have an example with real time data  and we could change the time period because it is the primary target of that library , worls with real time data,  i am not technical enought to do it, i am learning now javascript, vue etc ..., if someone can make such example it woulf be nice and more easy for many to test that library

**Comment by C451** [comment]
@adsonvinicius add more candles (It's known bug for small sets <= 5 candles or so)
@Edensplash Funny that the lib was initially designed for exploring static sets. There is test #7, very simple example of real-time data.

**Comment by Edensplash** [comment]
@C451  I was speaking about having an example in the demo with directly real-time instead of static data that we can directly see in one click, noy saying this is for only static data if not i will not be there looking at it

**Comment by adsonvinicius** [comment]
I had a dataset with 50 candles when that error occurred (scrolling left / zoom problem)

**Comment by C451** [comment]
@Edensplash oh yeah, sometime it will be live on the site. I have to admit that for now this project is more for "geek" traders - a lot of experimental features and rough parts. 

@adsonvinicius If you post a new issue following the template, that would be great.
