### ISSUE TITLE
Workflow for real-time data based on test example

### ISSUE THREAD

**Issue by adsonvinicius** [tvjsx/trading-vue-js#127]
I was checking the test example for real time data on [https://github.com/tvjsx/trading-vue-js/blob/master/test/tests/DataHelper.vue](DataHelper.vue) and the chat data process starts fetching data from an URL then it opens a WebSocket connection to retrieve data for updating. 

On this scenario the WSS data response is used just for add new candles? On a brand new candle the o,h,l,c data are created based on previous data assuming close value is equals to last value? What about the others such as timestamp and o,h,l? are they created based on previously data?

**Comment by arunavo4** [comment]
+1 I also, think a realtime websocket based example will be great.

**Comment by adsonvinicius** [comment]
After further reading I figured out when the first request is done (using the URL for each 15min) the chart "knows" from its definition that timeframe is 15min (mandatory ohloc data interval) so it starts a WSS connection and a "timer" is started, when a new value/volume is caught the chart "knows" this new value belongs to a new candle and it's added to an array to evaluate open, high, low and close (first value, max, min and last value from WSS).

I will just wait for someone confirm this idea.

**Comment by C451** [comment]
@adsonvinicius described more verbose that it actually is, but yeah that's correct.

With a new script system this part of DC will rewritten.
