### ISSUE TITLE
Volume overlay for negative numbers

### ISSUE THREAD

**Issue by adsonvinicius** [tvjsx/trading-vue-js#130]
I've read we can create our own overlay and plot on chart. I need to use MACD data which uses a histogram where bars where are shown for positive and negative values. 

The problem is the volume starts from the lower values so the idea is create "negative volumes", is there a way to plot using volume overlay?

**Comment by adsonvinicius** [comment]
UPDATE: I created an overlay cloning the built-in volume and changed the draw function on [volbar.js](https://github.com/tvjsx/trading-vue-js/blob/master/src/components/primitives/volbar.js) by the following code:

![Captura de Tela 2020-08-13 às 11 47 06](https://user-images.githubusercontent.com/14812507/90149329-c0395780-dd5a-11ea-8247-2031a57bda3a.png)

Once was cloned from library source overlay, is this a correct way to improve this functionality?

**Comment by C451** [comment]
It's better to create a completely new overlay. But anyways, Histogram overlay will be available in a few days.

**Comment by adsonvinicius** [comment]
Okay! I will wait then. At least when I was trying to create a new overlay I could understand the library deeper.
