### ISSUE TITLE
1.0 Version

### ISSUE THREAD

**Issue by marcossapp** [tvjsx/trading-vue-js#131]
@C451, first I want to say your library is amazing. Thanks by your contribution.

I was checking the roadmap and I could see some functionalities done, will you release all of them together or it will be as long as cards are done? My question is because I would like to use your library but some things are in WIP so I will have to wait for it.

BTW, is there any deadline for this version? The timezone setting is a very important thing (at least for me) because even if I do what you suggested in another Issue, for real-time (chart update method) is always considering UTC.

So, looking forward next releases!

**Comment by marcossapp** [comment]
@C451 I see, what about this timezone setting feature, it will be also available for real-time chart updates?

**Comment by adsonvinicius** [comment]
@marcossapp @C451  Is there any workaround to fix the real-time chart updates for timezone difference?

**Comment by OnlyC** [comment]
@adsonvinicius I edit src/components/js/botbar.js file (yeah, dirty hardcode). Plus or minus the amount of miliseconds you want.

functions: format_date & format_cursor_x
let d = new Date(t+25200000)

**Comment by adsonvinicius** [comment]
So, I should get the ohlcv with TS at UCT+0  and the bot-bar timestamp will be shown to my timezone just changing these functions? Even when chart-update-method (getting price/volume only) is called?
