### ISSUE TITLE
[Bug] Toolbar locks up on interval change

### ISSUE THREAD

**Issue by smcgovern** [tvjsx/trading-vue-js#132]
## Description
Depending on certain actions taken in certain orders it is possible for the toolbar to become locked up. There are workarounds to unlock it and to prevent it.

Example: https://tvjs.io/play/?a=nqqvzzmi

To cause the bug, select an interval to load from the the dropdown at the top left, if you attempt to use any toolbar tool once the `changeInterval()` is called action your toolbar will be locked up.

## Workarounds

If you activate a tool besides the crosshair tool prior to changing the interval, when the chart is redrawn the active tool is reset to crosshairs and the toolbar is not locked.

Another way to unlock it is if you have drawn items on the chart and the toolbar is locked up, you can select a drawn item then deselect it and the toolbar is unlocked.

## Data Sample (if applicable)

The data sample must follow the current [data structure](https://github.com/C451/trading-vue-js/tree/master/docs/api#data-structure-new).

## Console errors (if any)
None

## Additional Info 

trading-vue-js 0.6.1

**Comment by C451** [comment]
Fixed in 0.7.0 (the next version)
