### ISSUE TITLE
Tools pin positions are not getting updated up on adding offchart overlay

### ISSUE THREAD

**Issue by akjcodes** [tvjsx/trading-vue-js#138]
Can someone help me to fix this issue, I think we need to recalculate positions after adding an "offchart" overlay. But I'm not sure how it's done. Please check below images to understand the issues.

![before_atr](https://user-images.githubusercontent.com/15171292/92164361-dff00700-ee52-11ea-8296-e8e11d82b5b8.png)

![after_atr](https://user-images.githubusercontent.com/15171292/92164355-dc5c8000-ee52-11ea-94b2-83d51f6bc926.png)

**Comment by C451** [comment]
@akjcodes I need a full template to reproduce a bug.

**Comment by akjcodes** [comment]
@C451 Thanks for replying. You can follow these steps to see this on the demo

step 01 - Go to https://tvjsx.github.io/trading-vue-demo/
step 02 - Draw a line or Seg anything 
step 03 - On browser console please run this `DataCube.del('RSI')`

You will see all the pin points are getting misplaced 

Thanks.

**Comment by C451** [comment]
Fixed in 0.7.0 (the next version)

**Comment by akjcodes** [comment]
@C451 Thanks 👍. Any tips to fix it by my self?
