### ISSUE TITLE
Memory leak (Observed when running in loop)

### ISSUE THREAD

**Issue by test513607a** [tvjsx/trading-vue-js#139]
![Capture](https://user-images.githubusercontent.com/58187509/92417810-ca682f00-f129-11ea-98e0-b9ad075176de.PNG)
![Capture2](https://user-images.githubusercontent.com/58187509/92417812-cb00c580-f129-11ea-9228-de5724a49151.PNG)
[DataHelper.zip](https://github.com/tvjsx/trading-vue-js/files/5184980/DataHelper.zip)

## When running the load chart in a loop , the Memory occupied , as seen on TaskManager - > Chrome Tab continously increases by an increment of almost 10 MB (**wait for 10 iterations** to be there before the 10MB increment to be observed)
1) Unzip Datahelper.zip to Datahelper.vue, to be placed in the Tests, and go to Test 7 

2) Continuous fetch of btcusdt and loading to chart is done (ideally different products are fetched in a loop, just maintained btcusdt as the product for simplicity sake)

3) Observe the DevTools -> Sources (Capture.png , screenshot attached),
 Observe TaskManager -> Chrome -> particular tab increasing in memory (Capture2.png)

{  "version": "0.6.1", Windows 10, tried on Chrome/Firefox, npm ver 6.14.4}

## Data Sample (if applicable)

The data sample must follow the current [data structure](https://github.com/C451/trading-vue-js/tree/master/docs/api#data-structure-new).

## Additional Info 

(if needed to reproduce the issue) 

(tvjs version, OS, browser, npm version...)

**Comment by test513607a** [comment]
@C451 , in the Vue dev tools , I have seen that , 
after 10-15 iterations, 
on the 
emit custom-event (Candles)
emit custom-event (Grid)

occurrence, corresponds to the 10 mb increment 
Keep Vue dev tools->events open, and task manager open side by side, and monitor keenly

**Comment by C451** [comment]
That's your task man. It doesn't involve a full understanding of the logic, so waiting a solution from you.

**Comment by test513607a** [comment]
@C451  Oh, I thought you added me just as a viewer to monitor responses. My bad.

:), I would very much love to solve that. 
I have been on that over the complete long weekend, but in vain.
Done all the trials and errors on it, with all my limited JS, Vue JS knowledge. 

Any directions would be helpful, for me to take a look at it again

**Comment by vadymkop** [comment]
I have a similar situation with the memory leak. I created a repository with code which reproduce memory leak when I use the resetChart method many times.

Repository: https://github.com/vadymkop/TradingViewMemoryLeak

For run project do next:
1. Install dependencies with `npm install`
2. Run via `npm run serve`

In component "MemoryLeak" I created method updateChart. In this method, I created 2 cases for chart update with memory leak and without.

I hope it helps you to resolve the issue.

**Comment by C451** [comment]
@vadymkop nice, guys from TradingView.com also have a leak B)

**Comment by vadymkop** [comment]
Sorry it`s typo. I mean trading-vue.

**Comment by C451** [comment]
https://github.com/tvjsx/trading-vue-js/commit/996f83dd2a2cd9058ba1de1402959e0675431cb3 most likely solves the problem (at least for `resetChart()`)

**Comment by vadymkop** [comment]
@C451 Thank you )

**Comment by test513607a** [comment]
@C451 , @vadymkop  Thanks!

The rate of increase has decreased drastically, from 12 MB down to 3MB per iteration.

**Comment by C451** [comment]
@test513607a you can explore further. I found the leak by commenting different sub-components starting from the root comp (`trading-vue`)
