### ISSUE TITLE
Chart is not splitting dates

### ISSUE THREAD

**Issue by IlyaShkurenko** [tvjsx/trading-vue-js#141]
I'm pasting real stocks data and chart in not splitting bars instead there are breaks, for example there are free space if it were weekends. How to solve it?

**Comment by OnlyC** [comment]
You can set "indexBased": true to the option

https://github.com/tvjsx/trading-vue-js/tree/master/docs/faq

**Comment by C451** [comment]
I guess the "FAQ" word is not big enough. Thinking about changing the size to 200pt
