### ISSUE TITLE
Forcing TimeFrame Issue

### ISSUE THREAD

**Issue by marcossapp** [tvjsx/trading-vue-js#142]
Before open this as a proper issue I would like to ask if the system allows what I think it does:

I fetch 5 minutes candles but I want to show  them on each 15m, 30min, 1h etc. Is possible to force the chart timeframe to do that? In docs says it could be a number or any Constant.js map unit.

```
<trading-vue 
      :width="800"
      :height="600"
      :data="chart"
      :tf="timeframe">
</trading-vue>
```

Setting timeframe variable to a number (ms) is enough to do that?

**Comment by C451** [comment]
The `tf` parameter is used for different purpose: e.g. if you have renko chart it's hard to detect the correct interval from the data. What you need is Candles overlay on top of your main chart.

**Comment by marcossapp** [comment]
I see. I misunderstood then. By your timeframe example, I could see the
data is indexed by a timeframe and I thought it was changing this tf
parameter.

I use candles overlay on my main chart but it doesn't show candles grouped
by this param. Besides I'm using the index-based set as true which shows on
console a warning about needing to set the tf param.

So, does the system have a way to create candles based on some time
interval? Or do I need to recreate my ohlcv data for a new time interval ?

**Comment by marcossapp** [comment]
I see. I misunderstood then. By your timeframe example, I could see the
data is indexed by a timeframe and I thought it was changing this tf
parameter.

I use candles overlay on my main chart but it doesn't show candles grouped
by this param. Besides I'm using the index-based set as true which shows on
console a warning about needing to set the tf param.

So, does the system have a way to create candles based on some time
interval? Or do I need to recreate my ohlcv data for a new time interval ?

**Comment by C451** [comment]
The main chart determines the main tf, but overlays can be in any tf. Check the test#11. 
And also with scripts you can sample charts from the main data, test#14 (the chart should be shifted -3h, to be implemented):
```
return {
    props: { },
    conf: {
        renderer: 'Splines'
    },
    init: ``,
    update: `
        offchart(
			t % (3600000 * 4) === 3600000 * 3 ?
			[open4H, high4H, low4H, close4H] : NaN, 
			'4H', {type:'Candles', tf:'4H'}
		)
    `
}

```

**Comment by marcossapp** [comment]
Just to be more clear, In my case I have an ohlcv data for each 5min, so you mean the main chart will always show 5min candles unless I recreate this ohlcv to the new interval?

About the warning _**When using IB mode you should specify timeframe ('tf' filed in 'chart' object),otherwise you can get an unexpected behaviour**_ is shown on console on test 11, so should I ignore this warning anyway?

**Comment by C451** [comment]
It really depends on what you need. It can be the main 5m + 15,30,60 offchart. Or other way around. Obviously you cannot sample 5m from 15m with scripts.

Yea, ignore it. I left the chart without 'tf' on purpose. When `tf` is defined there should be no warn.

**Comment by marcossapp** [comment]
In my scenario I fetch data from a server, so getting different `ohlcv` for different timeframes from the same data it will cause a server overhead when multiple users are seeing their charts. I was just waiting your response to know whether I recreate my `ohlcv` data when changes the timeframe selector using client browser or if there was any setting I didn't find.

About the warn, what exactly should I set this `tf` param?

**Comment by C451** [comment]
I personally would download 1m and sample everything else. Obviously `tf` should be equal to the current main tf. If it's 5m candles then `tf: '5m'`

**Comment by marcossapp** [comment]
That's why I was thinking to do. When do you say this `tf` param where do you set when using DataCube? I search on docs but I coudn't figure out

**Comment by C451** [comment]
I updated the test#11 data, now it has all `tfs` and no warn.  Also you can
```
dc.set('chart.tf', '15m') 
```
Yeah, that's how easy it is.

**Comment by marcossapp** [comment]
I tried, however the warning I mentioned still shows up for this simple code:

```
this.chart = new DataCube({
     ohlcv: data['chart.data'],
})

this.chart.set('chart.tf', '15m')
```

Where data['chart.data'] is:

```
[ 1600077600000, 56.80, 57.33, 56.63, 57.05, 17090200 ]
[ 1600078500000, 57.07,  57.54, 57.04, 57.47,  12679440 ]
[ 1600079400000, 57.45, 58.00, 57.43, 57.77,  32371470 ], ...
```

**Comment by C451** [comment]
This is the exact reason why I require the full issue template. 
Alternatively, you can use https://tvjs.io/play

**Comment by marcossapp** [comment]
You're right.  I started as question and become an issue. I will do it.

**Comment by marcossapp** [comment]
@C451  I published on [tvjs](https://tvjs.io/play/?a=cliwggrg)

The warning is shown on console, and there's an error about timeframe setting. I guess I have misunderstood something but I thought this simple example should work.

**Comment by C451** [comment]
@marcossapp yes, there is a bug. To be honest there are a few of them. 
Luckily they are quite solvable.

**Comment by marcossapp** [comment]
I don't know if is related to this bug but when I change the ohlcv data to a new timeframe, setting this.chart to a new Datacube, I need to drag the screen to take effect. Besides the overlays don't show, which is strange once I reload the page with this new timeframe works fine.

**Comment by C451** [comment]
This is a workaround https://tvjs.io/play/?a=jx6inc1e for now

**Comment by marcossapp** [comment]
> This is a workaround for now https://tvjs.io/play/?a=jx6inc1e

The fact the timeframe is 30m and the candles are displayed on 15m each, is a normal behavior?

> > Besides the overlays don't show, which is strange once when I reload the page with this new timeframe works fine.
> 
> Yea, I think that will be good for another issue.

Ok

**Comment by C451** [comment]
@marcossapp yeah should be 15m, but it's just for displaying the workaround.

**Comment by marcossapp** [comment]
@C451 the point of having a forced timeframe set is not related to the main chart, but for off charts only, Is this correct?

The fix you made it was to remove the warn and make the https://tvjs.io/play/?a=cliwggrg working?

**Comment by C451** [comment]
Hey @marcossapp It's seems you have a lot of qs! Let's connect on discord, we can discuss the terms if you need a full support. 

Yes, the fix solves the problem, but your example still will not work, bc you can call `dc.set()` only on the next vue tick.

**Comment by feliperesilva** [comment]
Hi @marcossapp!

Were you able to resolve the TF alert issue?
What about the new information having no effect on the graph. Has anything been done?

Thanks!
