### ISSUE TITLE
Plotting stocks that is not continously trading for 24 hrs

### ISSUE THREAD

**Issue by dhannamarie** [tvjsx/trading-vue-js#143]
Hello, newbie here. I'm trying to plot stock prices that is not 24hrs trading and here's the result. There are empty intervals with no stock prices. I would like to ask what I could do to fix this such that the candlesticks should be continuously plotted. Thanks a lot.

![2020_09_23_02_30_46](https://user-images.githubusercontent.com/69465363/93923576-2647d000-fd46-11ea-8269-f350bb541b25.png)

**Comment by C451** [comment]
Hello, I'd recommend to explore the tests. You'll expand your knowledge about the lib significantly.

**Comment by dhannamarie** [comment]
> 
> 
> Hello, I'd recommend to explore the examples. You'll expand your knowledge about the lib significantly.
Will do. Thank you.
