### ISSUE TITLE
Lazy load of candles

### ISSUE THREAD

**Issue by novecento** [tvjsx/trading-vue-js#147]
Hi, and apologies in advance if question was already done.

Has anyone already implemented a lazy loading / progressive rendering of candles?

I'm able to show 100000 candles, for example, but it's very aggressive in terms of CPU and time, and it's not useful to do it all together, we can render or load progressively. 

Thanks a lot for this amazing tool.

**Comment by C451** [comment]
Hey, most likely that's an app-level problem. There is a basic example: https://github.com/tvjsx/trading-vue-js/blob/master/test/tests/DataHelper.vue . Obviously the full solution will be sightly more complicated.
