### ISSUE TITLE
With Live data feed, new bars goes out of visible charts, chart should display newest bar 

### ISSUE THREAD

**Issue by balwinderstock** [tvjsx/trading-vue-js#148]
How to reproduce: 
From Tests: In Play with DataCube in console [7/15]

Leave the chart for live update, after sometime new bars are created out they get out of visible canvas 

Expected:
Chart should adjust to show the newest bar  

![image](https://user-images.githubusercontent.com/72788092/95831203-618e5b00-0d56-11eb-8bd0-4c8cb6a55561.png)

**Comment by C451** [comment]
WIP https://github.com/tvjsx/trading-vue-js/blob/ed73a4e47c946ee6da1af752fe70d9a84bfdf95d/src/helpers/dc_core.js#L471

**Comment by balwinderstock** [comment]
Thanks, looking forward to it

**Comment by martinval** [comment]
I was looking for a solution ot this as well and while this is WIP my hack to update the scroll is to reset the chart when I click on it:

add @click.native="onClick" to the main chart comp and 

```
onClick(){
         this.$refs.tradingVue.resetChart()
     },
```

**Comment by C451** [comment]
@martinval should work already, reseting the chart too often is generally a bad practice.
