### ISSUE TITLE
How to create "windows"?

### ISSUE THREAD

**Issue by recoshet** [tvjsx/trading-vue-js#152]
Component [VueDraggableResizable 2](https://github.com/mauricius/vue-draggable-resizable) use [css transfroms](https://github.com/mauricius/vue-draggable-resizable/blob/e0f1a0ba8467f9d81d9def81db6aae59596dbb99/src/components/vue-draggable-resizable.vue#L781)
TradingVue.js has a bug, if use css transform https://github.com/tvjsx/trading-vue-js/issues/83
Tell me which way to go to create "windows" with drag and resizable functionality? And if possible with a zoom function (css transform scale).

**Comment by C451** [comment]
I need to explore ways to parse css-transforms to make the lib compatible.
For now I believe you can implement that with `position:absolute` and some js magic. 
Also look into this (drag&drop impl): https://github.com/tvjsx/trading-vue-js/blob/master/test/tests/Extensions/SettingsWin/dragg.js

**Comment by C451** [comment]
https://github.com/tvjsx/trading-vue-js/commit/1287d36e9ee2b0e6f52c13ba953d48acae899e4c 
Doesn't support zoom, I think it should implemented with resetting `width` & `height`
