### ISSUE TITLE
Dynamically removing and adding indicators

### ISSUE THREAD

**Issue by ArtemBondarenko1997** [tvjsx/trading-vue-js#153]
Good day. Your library is perfect for my task. Part of the business logic is adding and removing indicators from the chart. When I add everything is good. But when I remove the for example "ALMA" indicator, the line is not removed from the visible part of the canvas. Is it possible to fix this or am I doing something wrong? Here is the code:
//... 
computed: {
    //...
   chart() {
      return new DataCube(this.Data);
    }
}
, methods: {   
   addIndaicator(name) {
      if (this.indicators.includes(name)) {
        this.indicators.splice(this.indicators.indexOf(name), 1);
        this.Data.onchart = this.Data.onchart.filter(
          item => item.name !== name
        );
        return;
      }
      this.indicators.push(name);
      this.Data.onchart.push(this.indicatiorsData[name]);
   }
//..
}.
![image](https://user-images.githubusercontent.com/32524801/98000216-541c3c00-1dfd-11eb-948b-fe2136685b46.png)

(at image I don't show ALMA but line removet not all)
Thanks in advance!

**Comment by C451** [comment]
I need a better issue description. Please follow Full Template or Playground.

**Comment by ArtemBondarenko1997** [comment]
Ok, all application is very big. Tomorrow I will create playground with candles. Thank you for fast answer!

**Comment by Dav-id** [comment]
I noticed similar behaviour earlier. When I set visibility on an ALMA indicator using the display legend button on the indicator. In my case the data for the indicator was calculated at runtime by providing "data":[].

Clicking the display button toggles visibility on the hover value but the line remained visibile. 

The display button works fine with the PerfectTrades sample indicator where the data is part of the data.json file. I am not sure if this is relevant but it seems like it may have something to do with it (without looking into the underlying logic)

**Comment by C451** [comment]
@Dav-id need to check

**Comment by Dav-id** [comment]
@C451 Thanks for your response and looking into this. I followed the examples on the test cases and added the on_button_click event which works on indicators that are part of the core trading-vue-js library (SMA for example), but not with the tvjs-overlays library (ALMA for example). 

This is my first time using Vue so I am still find my way around it but from what I can tell my setup is correct. I include two relevant snippets below and a gif showing the difference between the two indicators. 

Very simplistic data example:

`
    "onchart": [
        {
            "name": "SMA, 5",
            "type": "SMA",
            "data": [
                [
                    1552453200000,
                    3958.5
                ],
                [
                    1552456800000,
                    3957.1
                ],
                [
                    1552460400000,
                    3952.3
                ],
                [
                    1552464000000,
                    3956.50529742
                ],
                [
                    1552467600000,
                    3948.4
                ],
                [
                    1552471200000,
                    3944.8
                ],
                [
                    1552474800000,
                    3928.7
                ]
            ],
            "settings": {"length":5}
        },
        {
            "name": "ALMA, 2",
            "type": "ALMA",
            "data": [],
            "settings": {"length":2}
        }
]`

on_button_click snippet:

`on_button_click(event) {
      if (event.button === "display") {
        let d = dc.get(event.type)[event.dataIndex];
        if (d) {
          if (!("display" in d.settings)) {
            this.$set(d.settings, "display", true);
          }
          this.$set(d.settings, "display", !d.settings.display);
        }
      }
    },`

![TradingVueJs 101 - Personal - Microsoft Edge Canary 2020-11-05 09-57-32](https://user-images.githubusercontent.com/172320/98226677-41654c80-1f4e-11eb-9364-714332dc0a46.gif)

**Comment by C451** [comment]
@Dav-id try to hide w/o the buttons, this works for me:
```tv.$set(dc.get_one('ALMA.settings'), 'display', false)```
Other wise I need a full app (MVP), good example is here https://github.com/tvjsx/trading-vue-js/issues/146

**Comment by C451** [comment]
Haven't seen the promised example, assume the problem is solved.

**Comment by devLukas10** [comment]
Hy, someone help me!, I'm trying to create new priceLine, and labels, How can I do it?
