### ISSUE TITLE
Block scroll

### ISSUE THREAD

**Issue by yammycode** [tvjsx/trading-vue-js#155]
Hello!
Can you please tell me if it is possible to block the zoom when scrolling the page. When I scroll the page and the cursor enters the chart, I can no longer scroll the page further. This is not always the correct behavior. For example, on google maps, to interact with the map you need to hold down the ctrl. How can I implement this here?

**Comment by C451** [comment]
Hi, yep now the lib uses the wheel exclusively. I'm thing about adding 3 modes: "prevent"(def), "pass", "click" (activate on click)
For now you can just comment these lines https://github.com/tvjsx/trading-vue-js/blob/master/src/components/js/grid.js#L278

**Comment by yammycode** [comment]
Thanks for help and great package!

**Comment by C451** [comment]
Boom, the feature is dropped hard https://github.com/tvjsx/trading-vue-js/commit/d59e0239dbdfd82f6b18a6646f09e0fb0bed6253

**Comment by yammycode** [comment]
Wow! Super, thanks a lot!
