### ISSUE TITLE
is it possible to capture click event on candle ? 

### ISSUE THREAD

**Issue by martinval** [tvjsx/trading-vue-js#159]
Hi, thanks for this really awesome tool.

I can't quite figure out from the docs whether its possible to click on a candle and get its data and index position.

I imagine this is what this.$refs.tradingVue.getCursor() is for, but I have trouble adding a click event to the main trading-vue component.... 

```
<trading-vue :data="timeseries" :width="width" :height="height" ref="tradingVue"  
        @click="test" ??????>
</trading-vue> 
```
Thanks in advance for any pointers

**Comment by C451** [comment]
For some reason std mouse events don't work on the main comp, but the alternatives are:
```
@click.native="onclick"
@grid-mousedown="onmousedown"
```

**Comment by martinval** [comment]
Thanks, works great 👍
