### ISSUE TITLE
Better "Why" in Readme

### ISSUE THREAD

**Issue by fuzzthink** [tvjsx/trading-vue-js#164]
Thank you for open sourcing something as/almost as impressive as tradingview's library.

In the "Why" section:
> This project created for algo-traders, data-driven investors and fund managers who value innovative approaches to market research. We all know that datasets become more and more complex and the old indicators, such RSI, Stochastics and trendlines cannot provide a strong edge.

Can you please tell me why tradingview's lightweight-charts can't do this? I'm trying to decide which library to use for my own "tradingview" app. Can you please what makes this better?

thanks.

**Comment by C451** [comment]
Hi, thanks John. The library already moved beyond a simple plotting lib (e.g. it supports scripts, web workers). Plus it'll be extended even further next year. I think lightweight-charts is a cool project if you need a compact hq charts. 

If you need to make extensive studies & more control over the process, I think this project will work better.

**Comment by Dav-id** [comment]
A simple reason not to use lightweight-charts is the fact they dont support sub / off-charts such as you would use with ATR, MACD etc. This feature has been long requested if you look at their open issues and I dont see them adding it any time soon.
