### ISSUE TITLE
use trading-vue-js in project

### ISSUE THREAD

**Issue by git1360** [tvjsx/trading-vue-js#166]
Is it possible use trading-vue-js as a chart component like chart.js with multi layer live data (for example EurUsd and GbpUSd) or draw line from server side data on chart ?
I work on algorithm trading program with c# net core 3.1 and To better understand and test the algorithms, I have to plot them on chart.

**Comment by C451** [comment]
Trading-vue shares 2d-canvas API for custom overlays. So (almost) everything is possible. 
For multi-currencies you can use 2 Candles overlays, or even 2 tvjs instances & link them with `chart-link` extension: https://github.com/tvjsx/tvjs-xp
