### ISSUE TITLE
chrome block  trading-vue.min.js

### ISSUE THREAD

**Issue by hossein2408** [tvjsx/trading-vue-js#173]
why chrome block  trading-vue.min.js ?

Content Security Policy of your site blocks some resources because their origin is not included in the content security policy header

![Untitled-1](https://user-images.githubusercontent.com/9799567/101388530-5890b480-38d5-11eb-979b-114a28676ea7.jpg)

**Comment by C451** [comment]
Need more data, just checked on chrome and got no issues. What's OS, did you get that on tvjs.io/play ?

**Comment by hossein2408** [comment]
in line 15911 trading vue js 
      this.worker = new Worker(URL.createObjectURL(blob));
this error :
Refused to create a worker from 'blob:http://localhost:15536/494ac1a3-04d2-4e38-84f1-518616d20898' because it violates the following Content Security Policy directive: "script-src * 'unsafe-inline' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
Uncaught DOMException: Failed to construct 'Worker': Access to the script at 'blob:http://localhost:15536/494ac1a3-04d2-4e38-84f1-518616d20898' is denied by the document's Content Security Policy.

i add this meta tag to my html header but not solved 
```
<meta http-equiv="Content-Security-Policy" content="default-src *; child-src * 'self' blob: http:; worker-src * 'self' blob:;
img-src * 'self' data: http:; script-src 'self' 'unsafe-inline' 'unsafe-eval' *;
style-src 'self' 'unsafe-inline' *"
```>

**Comment by hossein2408** [comment]
> Need more data, just checked on chrome and got no issues. What's OS, did you get that on tvjs.io/play ?

windows 10
visual studio 2019
.net core 3.1
i wanna run trading vue with js file with my data 
not with nodeJs server

**Comment by C451** [comment]
I couldn't reproduce this (I tried tvjs.io, demo, `npm run test`), none of them are showing the issue. So let's wait until someone confirm that.

**Comment by C451** [comment]
No further evidence, closing for now.
