### ISSUE TITLE
Errors when streaming candles into chart with initial empty data array

### ISSUE THREAD

**Issue by Dav-id** [tvjsx/trading-vue-js#177]
## Description

Basic scenario: I have an empty chart that I have specified a number of indicators on & off chart and I push candles into the trading vue component via dc.update and dc.set functions. 

On the first candle update I use dc.set to populate the data[] with a single candle then I use the set to update and add subsequent candles. However it seems for first several updates I receive a series of errors in my console. After a short period of time the candles kick in on the chart and the errors go away and everything works great. 

## Screenshot 

![e1](https://user-images.githubusercontent.com/172320/101822472-430fca80-3b21-11eb-9ba2-fd88ef903a31.png)
![e2](https://user-images.githubusercontent.com/172320/101822478-4440f780-3b21-11eb-8238-11283256e8c9.png)

## Code (MVP)

            onCandleUpdated({ candleObj }) {

                if (this.newRun) {

                    this.dc.set('chart.data', [[candleObj.time, candleObj.open.mid, candleObj.high.mid, candleObj.low.mid, candleObj.close.mid, candleObj.volune]]);

                    this.newRun = false;

                    this.$refs.tvjs.resetChart();

                } else {
                    this.dc.update({
                        candle: [candleObj.time, candleObj.open.mid, candleObj.high.mid, candleObj.low.mid, candleObj.close.mid, candleObj.volune]
                    });
                }
            },

## Data Sample 

```
dc: new DataCube({
                    "instrument": {
                        "symbol": "BKTST"
                    },
                    "chart": {
                        "type": "Candles",
                        "tf": "1m",
                        "data": []
                    },
                    "onchart": [
                        {
                            "name": "EMA, 9",
                            "type": "EMA",
                            "data": [],
                            "settings": { "length": 9, "display": true, "z-index": 20 }
                        },
                    ],
                    "offchart": [
                        {
                            "name": "ATR, 14",
                            "type": "ATR",
                            "data": [],
                            "settings": {
                                "length": 14
                            }
                        }
                    ]
                }),
```

## Additional Info 

Candles are pushed from SignalR to an event which is subscribed to in `created()` - also I've tried the following:
`
 mounted() {
            this.$nextTick(() => {
                this.$realtimeHub.$on('CandleUpdate', this.onCandleUpdated);
     });
}
`
tvjs : 0.10.0

**Comment by Dav-id** [comment]
Something I have noticed - Once the first candle closes and the second candle is pushed the chart appears to correct itself and the errors stop. So, it looks like as a minimum the chart is expecting two candle entries to be present in the DC.

**Comment by C451** [comment]
@Dav-id ty, I'll explore a bit later

**Comment by C451** [comment]
I checked the code, yep - 2 candles is a minimum requirement. I believe I fixed the `dc` error in the last commit.

**Comment by Dav-id** [comment]
Thanks @C451 ! From my preliminary testing, the errors appear to have been resolved. I will continue testing and update if they re-appear. Great job.
