### ISSUE TITLE
Constructing Bollinger Band

### ISSUE THREAD

**Issue by bangbangjim** [tvjsx/trading-vue-js#179]
I am trying to construct the Bollinger Band with the following onchart data:
```
        onchart: [ // Displayed ON the chart
        {
            "name": "EMA, 3",
            "type": "Bollinger Band",
            "data": [
                [ 1551128400000, 20, 38, 50],
                [ 1551132000000, 20, 38, 50],
                [ 1551135600000, 20, 38, 50],
                [ 1551139200000, 20, 38, 50],
                [ 1551142800000, 20, 38, 50],
            ],
    settings: {
        "color": "#42b28a"
    }
        },
    ],
    
```

I noticed that it wouldn't work unless the type is either SMA or EMA, which then can only accept an array of [timestamp, value]. 
Ideally I would want to input an array of [timestamp, low_band_value, mid_band_value, upper_band_value], is this possible at the moment? Where can I get the full list of available onchart type?

Thanks!

**Comment by adsonvinicius** [comment]
Do you have the ohlcv main data? If yes you don't need to add any Bollinger Band data. But if you want to use the Channel overlay as main chart you will get the same issue I had #172.

In my case I need to use the histogram overlay which accepts timestamp/value but I couldn't make it work properly.

**Comment by C451** [comment]
*Closed due to inactivity*
