### ISSUE TITLE
Blocking Zoom & Scroll

### ISSUE THREAD

**Issue by adsonvinicius** [tvjsx/trading-vue-js#181]
Is possible to block a chart from zoom and scroll? I tried to set max & min zoom values to same on chart config but still zoom out for less than 10 ohlcv data.

**Comment by C451** [comment]
*Closed due to inactivity*

**Comment by adsonvinicius** [comment]
@C451 Is there any way to block such events?

**Comment by C451** [comment]
@adsonvinicius Again, if it's a problem, let's see the full example. Tbh, I'm having hard time understanding what are you saying.

**Comment by adsonvinicius** [comment]
From the beginning: Imagine a chart like any possible chart using this library and I just want to know if there's any way to avoid this chart from scrolling and/or zooming. (working like a fixed image)

About the few candles behavior I can create a full example, but I think if the answer about the question below is needed to do it.

**Comment by C451** [comment]
You are an OG (how long do you use the lib?), it's time to finally read the code ;)

**Comment by adsonvinicius** [comment]
There are things I already changed, but I decided to ask because somebody can see faster (or had the same issue before) and avoid to debug step-by-step trying to find a solution. 

About scrolling I thought about set max and min candles to same number but it didn't work.

**Comment by adsonvinicius** [comment]
I found the hamster event on `grid.js `calling `this.listeners()`, so I just put:

```
if(this.$p.config.BLOCK_CHART === false)
    this.listeners()
```

And added this new config var. Simple like that.

Just to explain, I don't really like change the code because can be a mess with future commits, so even knowing the possibility of changing the code I asked because a config setting can solve a problem.

But, what really matters I could solve the problem and now is finally closed.
