### ISSUE TITLE
Bars type support

### ISSUE THREAD

**Issue by ctwhome** [tvjsx/trading-vue-js#182]
High, will be there an option to display the candles as **Bars**

**Comment by C451** [comment]
Yes, you starred the repo containing the overlay.

**Comment by ctwhome** [comment]
haha yes! The problem is that I couldn't make it work

**Comment by ctwhome** [comment]
Ah oke, I got it already. 
Once you enable the overlays package, it is possible to add the type 'XOhlcBars' to the chart. 
Thank you for this awesome library
![image](https://user-images.githubusercontent.com/4195550/102710797-1f811880-42b5-11eb-9153-3e0226787d6c.png)
