### ISSUE TITLE
goto not working properly when using indexBased

### ISSUE THREAD

**Issue by black-hawk85** [tvjsx/trading-vue-js#185]
## Description

goto-function jumps to any timestamp but not where I want to have it when I enable indexBased option.
As soon as I set indexBased to false it works correctly but the chart doesn't look nice because of market close timings.

It happens on any chart which has opening hours.
Let me know if you need more information.

(tvjs version: 1.0.0, OS windows/macOS/Linux, browser Chrome, npm version 6.14.8)

**Comment by C451** [comment]
Yes, I need the full program.

**Comment by black-hawk85** [comment]
[Playground goto.zip](https://github.com/tvjsx/trading-vue-js/files/5742937/Playground.goto.zip)

Have prepared App.vue and data.json for the playground, I hope I have set up everything correctly.
If you change indexBased to false in data.json the goto button (upper left) will jump to the desired timestamp

**Comment by black-hawk85** [comment]
hey, any news on this problem?
Do you need more data or infos?

**Comment by C451** [comment]
Problems with Index Based mode are usually complicated, you can use `goto(<index>)` for now.
