### ISSUE TITLE
VPVR support?

### ISSUE THREAD

**Issue by thebluefish** [tvjsx/trading-vue-js#189]
Hi,

I noticed VPVR support in the repo gif, but I cannot figure out how to use it in the library. Is this a published overlay?

![image](https://user-images.githubusercontent.com/4490910/104074922-3df87680-51c6-11eb-8f79-941e46867379.png)

**Comment by C451** [comment]
This is a paid overlay (in a testing phase). If you are interested, send a dm on discord.
