### ISSUE TITLE
Toolbar renders an empty frame

### ISSUE THREAD

**Issue by hesa2020** [tvjsx/trading-vue-js#191]
## Description
After setting the :toolbar variable to true, a white panel appears to the left of my chart however this panel is empty.
I assume its supposed to show the default methods if not overwritten. In the demo app nothing define the toolbar buttons.

Behaviour / expected behaviour

It renders the same buttons as in the demo.

## Screenshot 
![image](https://user-images.githubusercontent.com/2501581/104597306-29dbcb80-5643-11eb-863d-12834c244bdb.png)

## Code (MVP)
`<trading-vue
            ref="tvjs"
            :data="chart"
            :width="chartWidth"
            :titleTxt="chart.chart.titleTxt"
            :toolbar="true"
            :height="chartHeight - 40"
            :color-back="colors.colorBack"
            :color-grid="colors.colorGrid"
            :color-text="colors.colorText">
        </trading-vue>`

`<script>
    import TradingVue from 'trading-vue-js'
    import TDApi from '../connectors/TDApi'
    import moment from 'moment-timezone'
    import SymbolTracker from '../SymbolTracker'

    export default {
        name: 'Chart',
        components: { TradingVue },
        props: ['chartWidth','chartHeight'],
        mounted()
        {
            var self = this;
            this.$root.$on('symbol_changed', (symbol) =>
            {
                if(self.symbol != symbol)
                {
                    self.symbol = symbol;
                    TDApi.BindOnApiReady(async () => {
                        //TODO: Load history
                        var startDate   = moment().subtract(7,'d').tz("America/New_York").valueOf();
                        var endDate     = moment().tz("America/New_York").valueOf();
                        var response    = await TDApi.GetHistory(symbol, startDate, endDate);
                        if(typeof response != 'undefined' && response != false)
                        {
                            if(response.empty == false)
                            {
                                self.tickCandle = [];
                                self.ticks = [];
                                self.history = [];
                                for(var index in response.candles)
                                {
                                    if(index + 1 == response.candles.length)
                                    {
                                        var lastCandle = response.candles[response.candles.length - 1];
                                        self.tickCandle = [
                                            [
                                                moment(lastCandle.datetime).second(0).tz("America/New_York").valueOf(),
                                                candle.open,
                                                candle.high,
                                                candle.low,
                                                candle.close,
                                                candle.volume
                                            ]
                                        ]
                                    }
                                    else
                                    {
                                        var candle = response.candles[index];
                                        self.history.push([
                                            moment(candle.datetime).tz("America/New_York").valueOf(),
                                            candle.open,
                                            candle.high,
                                            candle.low,
                                            candle.close,
                                            candle.volume
                                        ]);
                                    }
                                }
                                self.chart.chart.data = self.history;
                                self.chart.chart.titleTxt = symbol;
                                self.$refs.tvjs.resetChart();
                                SymbolTracker.SubscribeToChartEquity(symbol);
                            }
                        }
                        // console.log(response);
                        // console.log(self.chart.chart.data);
                    });
                }
            });
            TDApi.BindOnApiReady(function()
            {
                //Minute
                TDApi.Stream.on('chart', function(data)
                {
                    if(data.service == 'CHART_EQUITY')
                    {
                        if(data.command == 'SUBS')
                        {
                            var candle = data.content[0];
                            if(candle.key == self.symbol)
                            {
                                if(self.ticks.length > 0)
                                {
                                    var keepTicks = [];
                                    var time = 0;
                                    var open = 0;
                                    var close = 0;
                                    var high = 0;
                                    var low = 999999999;
                                    var volume = 0;
                                    for(var index in self.ticks)
                                    {
                                        var tick = self.ticks[index];
                                        if(tick.tradeTime > candle.chartTime)
                                        {
                                            keepTicks.push(tick);
                                            if(time == 0)
                                            {
                                                time = moment(candle.datetime).second(0).tz("America/New_York").valueOf();
                                                open = tick.lastPrice;
                                            }
                                            close = tick.lastPrice;
                                            if(low > close)  low = close;
                                            if(high < close) high = close;
                                            volume += tick.lastSize;
                                        }
                                    }
                                    self.ticks = [];
                                    //Build the new tick candle
                                    self.tickCandle = [
                                        [
                                            time,
                                            open,
                                            high,
                                            low,
                                            close,
                                            volume
                                        ]
                                    ];
                                }
                                //
                                self.history.push([
                                    moment(candle.chartTime).tz("America/New_York").valueOf(),
                                    candle.openPrice,
                                    candle.highPrice,
                                    candle.lowPrice,
                                    candle.closePrice,
                                    candle.volume
                                ]);
                                self.chart.chart.data = self.history;
                            }
                        }
                    }
                });
                //Ticks
                TDApi.Stream.on('timesale_equity', function(data)
                {
                    if(data.service == 'TIMESALE_EQUITY')
                    {
                        if(data.command == 'SUBS')
                        {
                            for(var index in data.content)
                            {
                                var timesale = data.content[index];
                                if(self.tickCandle.length == 0)
                                {
                                    var time = moment(timesale.tradeTime).tz("America/New_York").valueOf();
                                    if(time > self.history[self.history.length - 1][0])
                                    {
                                        self.tickCandle.push([
                                            time,//0 Time
                                            timesale.lastPrice,//1 Open
                                            timesale.lastPrice,//2 High
                                            timesale.lastPrice,//3 Low
                                            timesale.lastPrice,//4 Close
                                            timesale.lastSize//5 Volume
                                        ]);
                                    }
                                }
                                else
                                {
                                    self.tickCandle[0][5] += timesale.lastSize;
                                    if(timesale.lastPrice > self.tickCandle[0][2]) self.tickCandle[0][2] = timesale.lastPrice;
                                    if(timesale.lastPrice < self.tickCandle[0][3]) self.tickCandle[0][3] = timesale.lastPrice;
                                    self.tickCandle[0][4] = timesale.lastPrice;
                                }
                                self.ticks.push(timesale);
                            }
                            self.chart.chart.data = self.history.concat(self.tickCandle);
                        }
                    }
                });
            });
            self.$refs.tvjs.resetChart();
        },
        data() {
            return {
                symbol: '',
                history: [],
                ticks: [],
                tickCandle: [],
                chart: {
                    chart: {
                        titleTxt: "",
                        type: "Candles",
                        data: [],
                        "tools": [
                            {
                                "type": "LineTool",
                                "settings": {
                                    "color": "#35c460"
                                }
                            },
                            {
                                "type": "LineTool:Extended",
                                "settings": {
                                    "color": "#3186c4"
                                }
                            }
                        ]
                    },
                    onchart: [],
                    offchart: [
                        {
                            name: "RSI, 20",
                            type: "RSI",
                            data: [
                                // [
                                //     1552525200000,
                                //     51.13050412634369
                                // ],
                                // [
                                //     1552528800000,
                                //     49.21384169575069
                                // ],
                                // [
                                //     1552532400000,
                                //     47.37895383765887
                                // ]
                            ],
                            settings: {
                                upper: 70,
                                lower: 30
                            }
                        }
                    ]
                },
                loading: true,
                errored: false,
                tb: true,
                colors: {
                    colorBack: '#fff',
                    colorGrid: '#eee',
                    colorText: '#333',
                }
            }
        }
    }
</script>`

## JSON Chart Data
https://pastebin.com/NVcdx8ke

"trading-vue-js": "^0.9.0",
Windows
Chrome 87

**Comment by C451** [comment]
DC is required for the toolbar.

**Comment by kempsteven** [comment]
what DC?

**Comment by lakshanperera** [comment]
@kempsteven DC means `DataCube`, refer [here](https://github.com/tvjsx/trading-vue-js/tree/master/docs/datacube)
