### ISSUE TITLE
Horizontal Scroll issue

### ISSUE THREAD

**Issue by oneart-dev** [tvjsx/trading-vue-js#193]
## Description

Horizontal Scroll issue
What is best way to fix it?

## Screenshot 

![scroll](https://user-images.githubusercontent.com/70148117/104811452-d5c81700-57fb-11eb-814e-56120cc54725.gif)

**Live example. Scroll horizontally.**
https://codesandbox.io/s/wandering-shape-w048l

Tested on Chrome
Using vuetify data table

**Comment by C451** [comment]
The lib doesn't support auto-sizing, you kinda need to update width & height.

**Comment by oneart-dev** [comment]
But the size doesn't change. It's just side scrolling.

**Comment by C451** [comment]
I don't know how vuetify data table works, but I can guess that it assumes relative positioning. The botbar uses it and the main chart doesn't.

So the only way to fix it is to somehow detect the container sizes and apply them to `trading-vue` component.

**Comment by oneart-dev** [comment]
Ok. I'll do it later

**Comment by oneart-dev** [comment]
I added live example to my post

**Comment by C451** [comment]
So the lib heavily uses `position: absolute`, in this case the `section` component is positioned against the left screen corner. If you add `position:absolute` to the "hello" container it solves the issue.

For CSS experts out there, is there a solution for relative ancestors? You can experiment with the example above (<div class="trading-vue-section"> is placed incorrectly).

**Comment by oneart-dev** [comment]
Sadly ``position: absolute`` is not an option in my case. Too much responsive hell happening and my CSS ability quite limited. But will try to play with it anyway

**Comment by Dav-id** [comment]
Either you can make #trading-vue-js{ position:absolute; } if you want it to be absolute to the screen. Alternatively make the #trading-vue-js{ position:relative; } to make it sit nicely in the div (I'd personally go with that one)

**Comment by C451** [comment]
@Dav-id @oneart-dev hey, this worked! I'm surprised.

**Comment by oneart-dev** [comment]
Thank you @Dav-id  It is totally works on my website as well. 
@C451 do you have logo for this project? happy to add it to the partners section. Really like it!

**Comment by C451** [comment]
Thanks @oneart-dev Let's make this a logo for now 
https://user-images.githubusercontent.com/48596328/104914866-d0580180-59a0-11eb-8adb-fa1763d9774d.png
