### ISSUE TITLE
Track pad sensitivity

### ISSUE THREAD

**Issue by oneart-dev** [tvjsx/trading-vue-js#195]
On my laptop I found working with chart quite hard.
Zooming in and out with track pad is like flying with speed of light. Same on tvjs website.

It is well known behavior. Probably you can check how it was fixed in this repo https://github.com/openseadragon/openseadragon/pull/754

Was tested on windows laptop dell XPS 13 on latest version of chrome browser.

**Comment by oneart-dev** [comment]
Also same behavior on quite old Lenovo laptop.

**Comment by C451** [comment]
Any ideas on how to fix this? 

Tested on my laptops, result: HP the trackpad is actually slower, Lenovo: works ok, but the panning is inverted.

**Comment by oneart-dev** [comment]
Take a look at facebook solution 
https://github.com/facebookarchive/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js

**Comment by oneart-dev** [comment]
Also you can check this thread https://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers

**Comment by C451** [comment]
Jeez, that fb code doesn't look good. Can you experiment on you laptops? 

https://github.com/tvjsx/trading-vue-js/blob/master/src/components/js/grid.js#L43
https://github.com/tvjsx/trading-vue-js/blob/master/src/components/js/grid.js#L378

I remember I was fighting with this to make it work on Mac Os. May be there is a quick fix for Windows (I guess that's the problem).

**Comment by C451** [comment]
@oneart-dev This problem is hard to catch. I'll reopen the issue if you are planning to contribute.
