### ISSUE TITLE
How can i add programmatically a tool on chart

### ISSUE THREAD

**Issue by hesa2020** [tvjsx/trading-vue-js#198]
Hello i currently save the drawings to a database and when you re-open the symbol on the chart i want to add those drawings back.

The saved data looks like this:

`{"name":"RangeTool 0","type":"RangeTool","settings":{"legend":false,"zindex":0,"selected":false,"state":null,"uuid":null,"p1":[1611340800000.0,839.5716176470588],"p2":[1611341820000.0,843.5212647058822]},"data":[],"grid":null,"id":"onchart.RangeTool0"}`

Note: My chart is index based and I replaced the indexes to timestamps.
By getting the candle at the index however this method does not works with candles in the future because they do not exists yet.

I tried using the following but it failed with error of undefined chart.type.

`dc.add('onchart', {
                                    type: 'LineTool',
                                    name: 'LineTool 0',
                                    data: [],
                                    settings: {
                                        p1: [1611354540000, 61.8843108108108],
                                        p2: [1611355680000, 61.86568918918918]
                                    }
                                });`

**Comment by C451** [comment]
Maybe `ti_mapping.js` will solve this.

**Comment by hesa2020** [comment]
@C451 This does fixed the convertion of index to timestamps and vise versa however adding the drawing to a chart using this method result in only adding the first point and the second one follow the cursor, also that drawing is not deletable and follows after chart reset.

Here is a gif [https://imgur.com/a/BbUi1In](https://imgur.com/a/BbUi1In)

**Comment by C451** [comment]
I believe here is a similar use 
case https://github.com/tvjsx/tvjs-xp/blob/main/src/extensions/chart-link/main.js#L263

**Comment by hesa2020** [comment]
> I believe here is the similar use case https://github.com/tvjsx/tvjs-xp/blob/main/src/extensions/chart-link/main.js#L257

This did fix it however one last issue, these newly added tools cannot be removed using the remove tool button.
