### ISSUE TITLE
Duplicate js file in builds when using tvjs-overlays and tvjs-xp

### ISSUE THREAD

**Issue by oneart-dev** [tvjsx/trading-vue-js#200]
my package.json
```
    "trading-vue-js": "^1.0.0",
    "tvjs-overlays": "^0.3.0",
    "tvjs-xp": "^0.3.0",
```
npm version v6.14.10

![image](https://user-images.githubusercontent.com/70148117/105846405-6d87eb00-5fdc-11eb-88a6-d9a12ffefc26.png)

For some reason it included 3 same libraries in dev build and 2 in prod build.
Any ideas why? It is at least 100kb (gz) plus to the build

**Comment by C451** [comment]
Yea, that's interesting, I guess that's some nmp magic. 
The builds themselves do not include the lib.

**Comment by oneart-dev** [comment]
Yeah, I checked both overlays and xp, same dependency. Also if I checked gzip version report it will show 2 instances. Main and XP. So, probably XP is the problem

**Comment by C451** [comment]
I think moving
```
"trading-vue-js": "^1.0.0"
```
to `devDeps` could solve the issue.

**Comment by oneart-dev** [comment]
Moving to devDeps fixed it. Thank you!
