### ISSUE TITLE
Passing custom data into overlay's data

### ISSUE THREAD

**Issue by vokomarov** [tvjsx/trading-vue-js#202]
Hey. 

I'm creating my custom overlay to draw lines. 

Example: 
![image](https://user-images.githubusercontent.com/8015167/106298207-49d2d800-625c-11eb-92d5-6859f0b606a3.png)

I'm trying to use overlay data to pass array of lines, but overlay receiving nothing:
```javascript
this.data.set('onchart.PriceLines0.data', [{
    type: 'solid',
    price: 0.013,
}]);
```

```javascript
draw(ctx) {
    console.log(this.$props.data); // Array[]
}
```

But I found that these data points are filtered by default, I assume for some optimisation to display only those points according current time window displayed. 

I found that I can trick it by adding some fake timestamp:
```javascript
this.data.set('onchart.PriceLines0.data', [[Date.now(), {
    type: 'solid',
    price: 0.013,
}]]);
```

But this solution is not suitable. I need to always display these lines.

Is there a way to disable filtering by first element of data arrays? I've tried to set `true` or `1` - doesn't working.

Thanks.

**Comment by vokomarov** [comment]
I've used overlay's `settings` instead of `data` as a workaround. 

```javascript
this.data.set('onchart.PriceLines0.settings', Object.assign(this.data.get('onchart.PriceLines0.settings')[0], {
    lines: prices,
}))
```

And inside overlay computed property:
```javascript
lines() {
    return this.$props.settings['lines'];
}
```

Works well. But doesn't seems to be a correct answer.

**Comment by C451** [comment]
@vokomarov Congrats, this Is the correct answer.
