### ISSUE TITLE
Web API datafeed

### ISSUE THREAD

**Issue by hossein2408** [tvjsx/trading-vue-js#203]
How can I use data feed except websocket
For example how can use a simple web api url without port number?

**Comment by eminvergil** [comment]
which api do you want to use ? is it a public api

**Comment by hossein2408** [comment]
I get data from binance exchange in one minute timeframe and make custom timeframe in server side
now I can show this candles with tradingvue but it is not live and should to refresh page

**Comment by eminvergil** [comment]
@hossein2408 i dont know anything about vue but i think your problem can solved with state machines. Here is a good documentation for you : https://www.phillipparker.io/articles/finite-state-machines-in-vue
