### ISSUE TITLE
[Question] Is it possible to set candle borders?

### ISSUE THREAD

**Issue by lucas-labs** [tvjsx/trading-vue-js#206]
Hi! First of all, thanks you all guys for this awesome library. Definitely the best charting lib out there.
I have a simple question. Is it possible to set a border to the candles? I'm trying to achieve something like this: 

![image](https://user-images.githubusercontent.com/12949236/107188129-e49e8580-69c5-11eb-9469-e441cc1b1ede.png)

Thanks in advance!!

**Comment by C451** [comment]
Thanks, you can make a custom overlay, changing `candle.js` primitive. 

Also, there's a chance it will be added to the tvjs-overlays repo.

**Comment by lucas-labs** [comment]
@C451 Thanks for the tip, I'll take a look at candle.js
Cheers!

**Comment by dearvn** [comment]
hi @C451 any update to more options as Heikin Aishi candle?
