### ISSUE TITLE
Chart type

### ISSUE THREAD

**Issue by elsandyid** [tvjsx/trading-vue-js#213]
It looks great for my needs, but I'he a question. Can I change the type of each chart I use? Like replace the candles with bars or something else?

**Comment by lakshanperera** [comment]
Yes, it is possible.
You can change the `chart.type` in the `DataCube` instance of your program to update the chart type.
```
chart.type='Candles'; // ==> CandleStick type
chart.type='Spline'; // ==> Line type
chart.type='XOhlcBars'; // ==> Bar type, but you need to install the free overlay pack
```
You can download the free overlay pack [here ](https://github.com/tvjsx/tvjs-overlays)

**Comment by lakshanperera** [comment]
Hi @elsandyid 

I don't think I have understood the question correctly, but if you are referring to the installation of the `tvjs-overlays` (free overlay pack), yes you have to install the `npm` package.

However, if you want to use few overlays only, you can also copy the relevant `.vue` component of the overlay (`xOhlcBars.vue` in your case) and the extra primitives that it uses to your project without installing the full `npm` package.

**Comment by lakshanperera** [comment]
Yeah but during development, we have to use `vue`, later it will be converted into just `html`and `js` (though DOM will be manipulated at runtime by `JS`)
