### ISSUE TITLE
Failed to build  the bundle

### ISSUE THREAD

**Issue by obxyann** [tvjsx/trading-vue-js#218]
Try to build the last  [bf576ab](https://github.com/tvjsx/trading-vue-js/commit/1f1603bd1d295b2487d395c5860a6dcb4200bd37) but failed
```
[webpack-cli] Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
```
but no problem after removed 'sourceMap: true,' in  webpack\build.config.js
```
    optimization: {
        minimize: true,
        minimizer: [new TerserPlugin({
            include: /\.min\.js$/,
            sourceMap: true, // <---remove this line
            extractComments: {
                banner: BANNER
            }
        })]
    },
```
My terser-webpack-plugin installed is v5.1.1
and also I can 't find 'sourceMap' option in [terser-webpack-plugin](https://webpack.js.org/plugins/terser-webpack-plugin/#options) ??

**Comment by C451** [comment]
https://github.com/tvjsx/trading-vue-js/commit/de8ce1af4d1c56036cae3c76d25fda86f8c7bf56
