### ISSUE TITLE
Proposal to build a library for svelte (trading-svelte)

### ISSUE THREAD

**Issue by slidenerd** [tvjsx/trading-vue-js#289]
- [Svelte has reached 1.0 a week ago.](https://svelte.dev/blog/announcing-sveltekit-1.0)
- Highly request you to consider building a version of this library that works on svelte

**Reason**

- Svelte does not use a virutal DOM and therefore lacks the runtime overhead that Angular, React and Vue come with. 
- This library would be a major addition to svelte ecosystem

**Comment by C451** [comment]
Ok, done! https://github.com/project-nv/night-vision
