### ISSUE TITLE
Marker html tooltip

### ISSUE THREAD

**Issue by DorothyRMartin** [tvjsx/trading-vue-js#32]
Ideally for each marker in data, if the included mouseover text could include html, this would be useful..

Rather than just having a trade marker saying '8%' .. . 

The marker could just be a signal, the tool tip could be the breakdown why that signal is there etc

**Comment by C451** [comment]
Yes, good idea.

**Comment by tiagosiebler** [comment]
Would love this too for a custom tooltip on hover

**Comment by koblents** [comment]
Hi! Do you have any updates here? Would love to have this feature
