### ISSUE TITLE
Add "labels" array to splines indicator overlay

### ISSUE THREAD

**Issue by tiagosiebler** [tvjsx/trading-vue-js#42]
With the "Splines" indicator type, you can plot multiple lines on one indicator:
```
var indicator = {
  name: "BBands",
  type: "Splines",
  data: [
    [timestamp, line1, line2, line3],
    [timestamp, line1, line2, line3],
    [timestamp, line1, line2, line3],
    [timestamp, line1, line2, line3],
    [timestamp, line1, line2, line3]
  ],
  settings: {}
};
```

I was thinking it could be useful for quick-starts if the colours and labels could be easily associated in the Splines indicator. Here's ideas for both in terms of format:
```
var indicator = {
  name: "BBands",
  type: "Splines",
  data: [
    [timestamp, line1, line2, line3],
    [timestamp, line1, line2, line3],
    [timestamp, line1, line2, line3],
    [timestamp, line1, line2, line3],
    [timestamp, line1, line2, line3]
  ],
  settings: {
    colors: [
      line1Color, line2Color, line3Color
    ],
    // OR
    seriesColors: [
      [timestamp, line1Color, line2Color, line3Color],
      [timestamp, line1Color, line2Color, line3Color],
      [timestamp, line1Color, line2Color, line3Color],
      [timestamp, line1Color, line2Color, line3Color],
    ],
    // labels
    labels: [
      line1Label, line2Label, line3Label
    ]
  }
};
```
The colours would let you easily either set a full series colour or a moving colour as the trend changes.

The labels would easily let you add some kind of legend to a Splines type indicator, such as this one:
![Screenshot 2019-08-14 at 10 53 09](https://user-images.githubusercontent.com/14090872/63085952-b530c900-bf46-11e9-8e24-2ebf8551a1bd.png)
 
Both features, if easy to add, would make it easier to work with Splines in a flexible way. I guess the answer is probably already "you can make your own overlay" 😄 but just in case this is something you (or someone else watching) is willing to enhance for others too!

**Comment by va-prans** [comment]
Yup I'd love this as well, especially the series colours !

**Comment by C451** [comment]
You can make your own overlay... Oh wait! 😄 

But seriously, this is a good idea for the SuperSplines overlay which can be in the overlay library.  It may also be a chance to contribute! (if you want / ready)

There may be many specific requests like this for the core lib, but unfortunately it will be hard to include them all. As I said earlier, I'd like to keep the main codebase very compact.

I'll probably enhance some of the overlays in the pre-release phase, but you can still make your own!

**Comment by C451** [comment]
*it's been a long time...*
