### ISSUE TITLE
Custom legendButtons with custom icon & tooltip

### ISSUE THREAD

**Issue by tiagosiebler** [tvjsx/trading-vue-js#43]
Loving the legendButtons feature - was actually super easy to hook up!

![Screenshot 2019-08-15 at 11 00 08](https://user-images.githubusercontent.com/14090872/63088117-e19b1400-bf4b-11e9-9f73-79767a049ebd.png)

Would love for a way to add my own custom buttons to this list.

An idea for how this might look, so you can set a custom icon and tooltip for that legend button:
```
            legendButtons: ['display','up','down','add','remove', 'mergeUp', 'mergeDown'],
            legendButtonDefinitions: {
              'mergeUp': {
                cssClass: 'fa fa-merge-up',
                htmlMarkup: '<i class="fa fa-merge-up"></i>',
                tooltip: 'Merge with section above'
              },
              'mergeDown': {
                ...
              }
            }
```

**Comment by C451** [comment]
Good idea, will save for the future.
