### ISSUE TITLE
Nuxt Support? ReferenceError: window is not defined

### ISSUE THREAD

**Issue by tyrauber** [tvjsx/trading-vue-js#72]
I'd love to use TradingVue in a Nuxt Universal App. I tried getting the simple example to work in Nuxt 2.6.2, but just the import declaration causes the ReferenceError: window is not defined. 

I created a simple example for demonstration / debugging purposes:
[nuxt-trading-vue](https://github.com/tyrauber/nuxt-trading-vue)

Just: 
$ npx create-nuxt-app nuxt-trading-vue
$ yarn add trading-vue-js

And added the example code.  Error is:

ReferenceError
window is not defined. 

node_modules/trading-vue-js/dist/trading-vue.js:17
```
		define([], factory);
	else if(typeof exports === 'object')
		exports["TradingVueJs"] = factory();
	else
		root["TradingVueJs"] = factory();
})(window, function() {
return /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
```

Any ideas?

**Comment by C451** [comment]
I'm not familiar with Nuxt yet, but I will check it. This looks like a similar issue: https://github.com/nuxt/nuxt.js/issues/2295

**Comment by C451** [comment]
How it's going?

**Comment by Mike-Kharkov** [comment]
I have the same problem.
Does anybody have an idea how should I fix it?

**Comment by HerrBertling** [comment]
@Mike-Kharkov following [the nuxtjs docs](https://nuxtjs.org/guide/plugins#client-or-server-side-only), I did this:

- Install the package, of course.
- Create `trading-vue.client.js` file in the `plugins` folder with this content:

```js
import Vue from 'vue'
import TradingVue from 'trading-vue-js'

Vue.use(TradingVue)
```

- Add the plugin within `nuxt.config.js` => `plugins: ['~/plugins/trading-vue.client.js'],`
- Copy&Paste the "[Minimal working example](https://github.com/tvjsx/trading-vue-js#how-to-use)" into the page you want to use the chart
- See chart

![image](https://user-images.githubusercontent.com/1827373/86962282-ec155c00-c162-11ea-9564-8b997bcc7de3.png)

- ???
- Profit 💸 💸 💸

**Comment by Bearfinn** [comment]
I am using this with Nuxt.
Using the main `<trading-vue>` components works perfectly; however, the problem still exists when I tried to import the `Overlay` mixin.
I have notices this is SSR issue where the code is executed on server side and it couldn't find `window` object, but I couldn't get my head around it.

### Reproduction Steps
1. Repeat the process above
2. Create new indicator file
```
// components/IndicatorSetups.js
import { Overlay } from 'trading-vue-js'

export default {
  name: 'Setups',
  mixins: [Overlay],
  methods: {
    draw(ctx) { // draw soomething }
  },
  use_for() {
    return ['Setups']
  }
}
```
3. Pass overlay file to main component
```
// pages/main.vue
<template>
     <trading-vue
        v-if="trading.chart.data"
        :data="trading"
        :overlays="overlays"
      ></trading-vue>
<template>
<script>
import IndicatorSetups from '~/components/IndicatorSetups'

export default () {
   data() {
    return {
      trading: {
        chart: {
          type: 'Candles',
          data: null,
          indexBased: true,
          tf: '1d',
        },
        onchart: [
          {
            name: 'Setups',
            type: 'Setups',
            data: [],
            settings: {},
          },
        ],
      },
      overlays: [IndicatorSetups],
    }
   }
}
```

### What I have tried
1. Extract the `<trading-vue>` to new component to do lazy import
2. Wrap `<trading-vue>` with `<client-only>`
3. User `process.client` to import mixin
4. Use import callback `() => import('trading-vue-js')`

**Comment by C451** [comment]
@Bearfinn would be awesome if you create a small repo with all deps that tries to use tvjs + nuxt. 
And we can go from there. When it's solved we would have an example that I could pin somewhere in the docs.

**Comment by Bearfinn** [comment]
I have created the repository with the code
See: https://github.com/Bearfinn/trading-vue-js-nuxt-overlay/tree/master

You can see it working if you commen out the `import {Overlay} from 'trading-vue-js'` and `data.overlays` in `index.js`
Thank you for your immediate response!

**Comment by C451** [comment]
@Bearfinn cool, I'll experiment with it

**Comment by csabaxyz** [comment]
For reference, I solved it by using the previously mentioned `trading-vue.client.js` file in the `plugins` directory, like so:
```js
import Vue from 'vue'
import TradingVue from 'trading-vue-js'
import ChartOverlays from 'tvjs-overlays'
import ChartExtensions from 'tvjs-xp'

Vue.use(TradingVue)

export default ({ app }, inject) => {
  inject('chartExtensions', ChartExtensions)
  inject('chartOverlays', ChartOverlays)
}
```

Later I can access them anywhere like `this.$chartOverlays`. But of course, you can use mixins, or other methods as well.

For some reason the chart doesn't render when I add all the extensions to it, because it says:
```
_this2.dc.get is not a function
```

But that's another issue.

**Comment by C451** [comment]
It looks like nuxt.js messes up the lib quite well. 2be investigated
If there are other people who figured this out to some degree, feel free to share here.

**Comment by C451** [comment]
@Bearfinn so yeah, the method by @csabaxyz solves your particular problem: 

```js
import Vue from 'vue'
import TradingVue from 'trading-vue-js'
import SetupIndicator from '~/components/SetupIndicator';

Vue.use(TradingVue)

export default ({ app }, inject) => {
    inject('SetupIndicator', SetupIndicator)
}

```

```js
 overlays: [this.$SetupIndicator]
```
That's what interesting now `_this2.dc.get is not a function`

**Comment by C451** [comment]
@csabaxyz This solves your issue (DataCube was needed) 
https://github.com/tvjsx/trading-vue-nuxt

The remaining q is why all the injections are initially `undefined`. Maybe some Nuxt-pro can tell us.

**Comment by C451** [comment]
*no progress, let's assume this is solved*
