### ISSUE TITLE
How can I add more tools like this:

### ISSUE THREAD

**Issue by activeliang** [tvjsx/trading-vue-js#95]
![](https://biwenying-1254277363.cos.ap-guangzhou.myqcloud.com/Pasted%20Graphic.png)

**Comment by C451** [comment]
For now it's undocumented, but in a nutshell you need to clone and change https://github.com/C451/trading-vue-js/blob/master/src/components/overlays/LineTool.vue 

and add it as a custom overlay. A good idea for a mini tutorial.

**Comment by C451** [comment]
Overlay's guide touches upon this https://github.com/tvjsx/trading-vue-js/blob/master/docs/guide/OVERLAYS.md
